# Numpy Assignment

In [2]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

In [4]:

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
import numpy as np
def matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

inputvector = np.array([10,20,30,40,50,60,70,80,100])
k = 4
op_matx_dec_order = matrix(inputvector,k,False)
#op_matx_inc_order = gen_vander_matrix(inputvector,k,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",k,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")



------------OUTPUT-------------

The input array is: [ 10  20  30  40  50  60  70  80 100] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[   1000     100      10       1]
 [   8000     400      20       1]
 [  27000     900      30       1]
 [  64000    1600      40       1]
 [ 125000    2500      50       1]
 [ 216000    3600      60       1]
 [ 343000    4900      70       1]
 [ 512000    6400      80       1]
 [1000000   10000     100       1]] 



In [9]:
# Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [123]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k= 3
cumsum, moving_aves = [0], []

for i, x in enumerate(mylist, 1):
    cumsum.append(cumsum[i-1] + x)
    if i>=k:
        moving_ave = (cumsum[i] - cumsum[i-k])/k
        moving_aves.append(moving_ave)

print(moving_aves)        
print('The moving average sequence has {} values.'.format(len(mylist) - k + 1))

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
The moving average sequence has 11 values.
